// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwq6y3RRFnQfwfh1QG4hdWj85TZaGyS3M',
    appId: '1:338312884612:web:7dc0729bc0e3674a25edd1',
    messagingSenderId: '338312884612',
    projectId: 'cantillana-report-app',
    authDomain: 'cantillana-report-app.firebaseapp.com',
    storageBucket: 'cantillana-report-app.firebasestorage.app',
    measurementId: 'G-4HE3ZBR3DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3ZbfbFM7eQoBDYVkiQj2HDdPXiFUa-0',
    appId: '1:338312884612:android:26fcf88c6202717f25edd1',
    messagingSenderId: '338312884612',
    projectId: 'cantillana-report-app',
    storageBucket: 'cantillana-report-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByACs7gU2yB1O1JWf5nZxgqqbl13f47oU',
    appId: '1:338312884612:ios:f6e7735c380aa75925edd1',
    messagingSenderId: '338312884612',
    projectId: 'cantillana-report-app',
    storageBucket: 'cantillana-report-app.firebasestorage.app',
    iosBundleId: 'com.example.appincidencias',
  );
}
